version: '2'
services:
  app:
    build: .
    links:
      - postgres
      - redis
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
  postgres:
    image: postgres:11.7
    env_file:
      - .postgres.env
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:5.0.8
volumes:
  postgres:

